apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: contentful-core.php 
  description: This package provides foundation components for both the Delivery and Management SDKs for PHP.
  annotations:
    github.com/project-slug: contentful/contentful-core.php 
    contentful.com/service-tier: "4"
  tags:
    - tier-4
spec:
  type: library 
  lifecycle: production
  owner: group:team-developer-experience
